### ISSUE TITLE
Android: freeze when running the Javascript Remote Debugger

### ISSUE THREAD

**Issue by tomLadder** [okgrow/react-native-copilot#102]
**Current Behavior**
I am facing an issue with this awesome library when running the React-Native Javascript Remote Debugger on Android. It seems that the javascript thread is fully utilized.

![image](https://user-images.githubusercontent.com/20393156/51731774-4e1bf780-207c-11e9-8f5d-f909f5ee5069.png)

If i disable the debugger everything works as expected. iOS is also working.

**Input Code**
```js
<CopilotStep name="text" order={1} text="Search for a cow.">
  <SearchBar
    placeholder={translate("COW_FILTER")}
    onChangeText={this.updateSearchQuery}
    onPress={this.openModal}
    onLayout={this.onLayout}
    image={AssetsManager.icons.filter}
  />
</CopilotStep>;

```

**Environment**
- OS: Android
- `react-native-copilot`: 2.4.1
- `react-native`: 0.56.0

**Additional Context**

`react-native-svg` is not installed.

**Comment by switch13** [comment]
Hi @tomLadder , 

How did you fix this? I'm running into the same issue but the exact opposite is happening for me. When I DON'T have remote debugger running, I'm frozen. When I turn it on it starts working. 

Thanks in advance!
