### ISSUE TITLE
Is it possible to apply styles?

### ISSUE THREAD

**Issue by rdcalle** [okgrow/react-native-copilot#11]
- modal (color, opacity...)
- steps (about the look of the steps)
- buttons (style and text values as well)

**Comment by mohebifar** [comment]
Currently, it's not possible. But it's something we can plan to implement for v1.1.

**Comment by mohebifar** [comment]
In version 2, now you can specify a custom tooltip component:

https://github.com/okgrow/react-native-copilot/blob/master/README.md#custom-tooltip-component
