### ISSUE TITLE
App shows all steps together, instead of showing them step by step  

### ISSUE THREAD

**Issue by Luckygirlllll** [okgrow/react-native-copilot#16]
I have added 3 steps, I thought that they will display one by one, however, they all displayed together at the same time. Why is that? 

```
import { copilot,walkthroughable, CopilotStep } from '@okgrow/react-native-copilot';
const CopilotText = walkthroughable(Text);

class Home extends Component {

render() {
return (
  <View>     
    <CopilotStep text="step 1" order={1} name="openApp">
       <CopilotText>Step 1 !</CopilotText>
    </CopilotStep>
    </View>
    <View>
      <CopilotStep text="Step 2" order={2} name="openApp2">
       <CopilotText>Step 2!</CopilotText>
    </CopilotStep>
    </View>
    <View>
    <CopilotStep text="Step 3!" order={3} name="openApp3">
       <CopilotText>Step 3</CopilotText>
    </CopilotStep>
    </View>
)}
}


export default copilot()(Home);



```

**Comment by mohebifar** [comment]
I see all the steps are named `openApp`. Try giving different names to them.

**Comment by Luckygirlllll** [comment]
@mohebifar I have already tried that, it didn't help! I saw that in example used this.props.start(), to invoke the  steps, but in example in the GitHub CopilotSteps inside the render method, so I'm not sure how should I invoke start of the work of the CopilotSteps.

**Comment by Luckygirlllll** [comment]
@RichardLitt @mohebifar Please take a look at my code, what else should be in that component to make it work correctly? how to trigger starts of steps?

**Comment by mohebifar** [comment]
@Luckygirlllll Could you please give it another try with version 2?

**Comment by mohebifar** [comment]
Closing this for now. Feel free to re-open it if you are still seeing the issue.
