### ISSUE TITLE
Copilot steps doesn't display in the screen 

### ISSUE THREAD

**Issue by Luckygirlllll** [okgrow/react-native-copilot#17]
This is my code, what should I do to see Copilot steps which will show hints one by one? 
I saw that in example there is props.start() to start the tutorial, however, how to make it work, if Copilot steps inside the render function?   

```
import { copilot,walkthroughable, CopilotStep } from '@okgrow/react-native-copilot';
const CopilotText = walkthroughable(Text);

class Home extends Component {

render() {
return (
  <View>     
    <CopilotStep text="Hint 1" order={1} name="openApp">
       <CopilotText>Step 1 !</CopilotText>
    </CopilotStep>
    </View>
    <View>
      <CopilotStep text="Hint 2" order={2} name="openApp2">
       <CopilotText>Step 2!</CopilotText>
    </CopilotStep>
    </View>
    <View>
    <CopilotStep text="Hint 3!" order={3} name="openApp3">
       <CopilotText>Step 3</CopilotText>
    </CopilotStep>
    </View>
)}
}

export default copilot()(Home);
```

**Comment by Luckygirlllll** [comment]
it seems that I need to use

```
componentWillMount() {
    this.props.start();
}
```
In order to make it start

**Comment by RichardLitt** [comment]
Thanks for logging, @Luckygirlllll! Is this ready to be closed, then?

**Comment by Luckygirlllll** [comment]
@RichardLitt Yes, however, I would recommend too you update Readme file, as I have spent 1 day, trying to figure out why library doesn't work, I guess other users can experience same issue!

**Comment by RichardLitt** [comment]
That's a good point! But you may be the best person to make that PR 😃. Would you like to do it?

**Comment by mohebifar** [comment]
I added that to the README earlier today. If there's anything else you'd like to add, your PRs are very welcome!

**Comment by Luckygirlllll** [comment]
@mohebifar Awesome, thanks! Probably mention about this [bug](https://github.com/okgrow/react-native-copilot/issues/18) would be useful as well in the README! :)
