### ISSUE TITLE
How to use react-native-copilot with react-native-navigation

### ISSUE THREAD

**Issue by daryllukas** [okgrow/react-native-copilot#20]
I'm trying to add a `CopilotStep` to a navigator button (refer to [`react-native-navigation` docs](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator))

I'm not sure where to start. Please help.

`@okgrow/react-native-copilot` version: 1.0.1
`react-native-navigation` version: 1.1.305
`react-native` version: 0.46.4

**Comment by mohebifar** [comment]
I believe it's not doable with `react-native-copilot` since it seems that the navigator buttons are not actually *React* components.

**Comment by daryllukas** [comment]
Okay. Thank you.

**Comment by somangshu** [comment]
The only way to do this would be to create a UI in a stack navigator which looks like the replica of your base screen and use only react native elements to complete the walk-through on the Replica screen itself. Once completed a key could be set in the async store based on which this component shall load(or not).

**Comment by ys-sherzad** [comment]
@daryllukas I'm wondering if you have found a way to implement this with `react-native-navigation` and if not, what other solutions did you adapt, if I may ask :)
