### ISSUE TITLE
All copilot always steps are shown in the top left corner of the screen. [bug]

### ISSUE THREAD

**Issue by YuryKorovko** [okgrow/react-native-copilot#23]
Hi! I  just cloned your copilot example app and all steps always are shown in the top left corner of the screen.
No changes in your code were done.

![img_0301](https://user-images.githubusercontent.com/16955777/39480081-d0698c24-4d6f-11e8-938a-da5344d30caf.PNG)
![img_0302](https://user-images.githubusercontent.com/16955777/39480082-d08b31c6-4d6f-11e8-95c4-f59a4d6b3cfc.PNG)
![img_0303](https://user-images.githubusercontent.com/16955777/39480083-d0aa8f4e-4d6f-11e8-821d-5f66f5343fdf.PNG)

**Comment by mohebifar** [comment]
It should be fixed in 3c23125. Could you please try again?
