### ISSUE TITLE
Allow prop for running the first time a user opens the app

### ISSUE THREAD

**Issue by ErkanSensei** [okgrow/react-native-copilot#3]
I think it'd be useful to be able to pass a prop to only display the tutorial when the prop is true. This way, we could use a variable to check if it's the first time a user has opened the app, thus prompting the tutorial.

**Comment by mohebifar** [comment]
You can actually invoke the `start` function whenever needed:

```js
componentWillMount() {
  if (firstTime) {
    this.props.start();
  }
}
```

**Comment by ErkanSensei** [comment]
Ah, I didn't realize that there was a start function. Did I just miss it in the docs or the example?

**Comment by mohebifar** [comment]
With `v2.1.0` you can now start the tutorial in `componentDidMount`.
