### ISSUE TITLE
Use copilot with custom native-base components

### ISSUE THREAD

**Issue by dirkvanherpen** [okgrow/react-native-copilot#31]
It seems not possible to highlight buttons in the walkthrough. 
I call `this.props.start();` so that shouldn't be the problem. It might have to do with the custom components in native-base. If we are using the normal components it works perfectly, but with the custom components, it won't.
![image](https://user-images.githubusercontent.com/23356823/40281528-76c418da-5c63-11e8-8734-f8561d6268f2.png)

How can I make copilot work with custom native-base components?

**Comment by mohebifar** [comment]
Is it `Button from 'native-base'` or `Button from 'react-native'`? If you don't have access to the underlying component's code (being a third-party lib), one possible workaround is to wrap it within a `View` component.

Only "native" components can be made walkthroughable using the `walkthroughable` helper.

[https://github.com/okgrow/react-native-copilot#custom-components-as-steps](https://github.com/okgrow/react-native-copilot#custom-components-as-steps)

**Comment by dirkvanherpen** [comment]
Thank you for the quick reply. It worked for me, meaning I get a step-by-step walkthrough, but the position of the highlights doesn't match the position of the buttons. 

Code:
![image](https://user-images.githubusercontent.com/23356823/40414805-8f8f0b50-5e79-11e8-813d-e893d53f773c.png)

Application:
Step 1:
![image](https://user-images.githubusercontent.com/23356823/40414959-fdc038e2-5e79-11e8-886e-fca3cf5033af.png)
Step 2:
![image](https://user-images.githubusercontent.com/23356823/40414938-f04f5e5e-5e79-11e8-9074-b9988309cce8.png)


Any idea how i can fix this?

**Comment by mohebifar** [comment]
Could you please confirm that you're using v2.2.2?
v2.2.1 was buggy on Android having the same positioning issue and got fixed just last week.

**Comment by dirkvanherpen** [comment]
I can confirm that I am using v2.2.2.

![image](https://user-images.githubusercontent.com/23356823/40425815-bd51558c-5e99-11e8-9412-bf9220121170.png)

**Comment by mohebifar** [comment]
Okay, thanks. I'm curious to see what happens with 2.2.1.

**Comment by dirkvanherpen** [comment]
I have already tried version 2.2.1, but I still have the same problem.

**Comment by mohebifar** [comment]
It'd be good if you share a minimal code that helps me reproduce this issue.

**Comment by dirkvanherpen** [comment]
I tried version 2.2.3 and 2.2.4, but I still have the same issues with both versions.

v2.2.3
![image](https://user-images.githubusercontent.com/23356823/40577549-e6379b4e-6107-11e8-82a8-c699ae3f754d.png)
 v2.2.4
![image](https://user-images.githubusercontent.com/23356823/40577599-7994a986-6108-11e8-89bd-9afb0e1cb08c.png)

**Comment by dirkvanherpen** [comment]
I have tried multiple versions to try to fix this, but I can't get the highlight parts exactly on the button. 
Any idea how to fix this?

**Comment by Vishal-Lakkapathri** [comment]
Facing the same issue when used with https://wix.github.io/react-native-navigation.
Need Help!!

**Comment by sujitpk-perennial** [comment]
Hello team, I am able to show the copilot UI for iOS properly. But for Android, the UI is not showing proper place. Also text also not visible. I am using "@okgrow/react-native-copilot": "^2.2.6"

![screen shot 2018-06-13 at 3 22 10 pm](https://user-images.githubusercontent.com/23031821/41345221-aef3f41c-6f20-11e8-808a-b5bed8d2c532.png)

**Comment by RichardLitt** [comment]
@mohebifar Can you take another look at this, please?

**Comment by mohebifar** [comment]
@sujitpk-perennial It is really hard to figure out what the issue is without being able to reproduce it. It would be great if you could provide a very minimal expo snack or a gist to help me reproduce this.

**Comment by sujitpk-perennial** [comment]
@mohebifar I found that 
1. In style.js 
`tooltipText: {  } ` 
```
When I added like 

tooltipText: {
    color: 'rgba(20,20,20,1)'
  }
```
  Then I am able to see the color for text in Android. 
  
2. In CopilotModel.js file, I found one condition that

     ```
if (this.props.androidStatusBarVisible && Platform.OS === 'android') {
       obj.top -= StatusBar.currentHeight; // eslint-disable-line no-param-reassign
     }

```   
   When I commented `obj.top -= StatusBar.currentHeight;` then I am able to see the badge number properly.

**Comment by danielang** [comment]
You can add:
```javascript
copilot({
    androidStatusBarVisible: false
}),
```
