### ISSUE TITLE
Unable to edit number components in the CoPilot Modal

### ISSUE THREAD

**Issue by SebastianKurp** [okgrow/react-native-copilot#38]
Hey,
I'm trying to edit the stepNumber style in the CoPilot modal so it suits my app's theme better. The only way currently I know how to do this is to edit the modules style directly. I figured since this is a new module changes will be made frequently so a fork would be less than ideal. Any solutions to this? 

The Code below is in CopilotModal.js, it references the style I would like to have the ability to edit.
```
renderTooltip() {
    const { tooltipComponent: TooltipComponent } = this.props;

    return [
      <Animated.View
        key="stepNumber"
        style={[
          styles.stepNumber,
          {
            left: this.state.animatedValues.stepNumberLeft,
            top: Animated.add(this.state.animatedValues.top, -STEP_NUMBER_RADIUS),
          },
        ]}
      >```

**Comment by danielang** [comment]
Should be solved by PR #41
