### ISSUE TITLE
Detecting end of bubble tutorial

### ISSUE THREAD

**Issue by sujitpk-perennial** [okgrow/react-native-copilot#39]
I want to detect the end of the bubble tutorial in the app so that I can perform other operations. Is there any way to detect.

**Comment by mohebifar** [comment]
You can use the `copilotEvents` prop in the root component to register event listeners. You can specifically listen for the `stop` event:

```js
this.props.copilotEvents.on('stop', () => {
  console.log('Tutorial stopped');
})
```

**Comment by sujitpk-perennial** [comment]
@mohebifar Thanks a million.
