### ISSUE TITLE
Need more tutorial! help wanted

### ISSUE THREAD

**Issue by eugene-zheng0208** [okgrow/react-native-copilot#4]
I followed your tutorial but couldn't see any tour guide both on android and ios.
It would be grateful if more detailed tutorial

**Comment by mohebifar** [comment]
Now, we have the [example](https://github.com/okgrow/react-native-copilot/blob/master/example/App.js). Also added more info to the readme. Closing this for now, feel free to re-open this issue if there is still anything unclear.
