### ISSUE TITLE
Get notified when copilot ends

### ISSUE THREAD

**Issue by ohtangza** [okgrow/react-native-copilot#44]
Currently, there is no way we can continue after the copilot ends. Registering a event handler for it would be nice.

**Comment by RichardLitt** [comment]
Thanks for opening an issue for this, @ohtangza. That sounds like a good idea to me. Would you be willing to open a PR for this?

**Comment by ohtangza** [comment]
@RichardLitt Yeap, I do have a plan to open PR by the end of this week. :) Give me some time until I drafted my work :)

**Comment by RichardLitt** [comment]
No rush. Thanks @ohtangza :)

**Comment by mohebifar** [comment]
Sorry for the late reply, I was on a vacation last week. This feature actually exists and I have explained the solution in a comment in #39. But it's missing in the docs. I'd try to add this to the README. PRs are also welcome.

**Comment by RichardLitt** [comment]
Thanks, @ohtangza! I'm sorry if I caused you to duplicate work; my bad. We'll add this to the README.

**Comment by ohtangza** [comment]
@RichardLitt That's alright. Hope to see an improved documentation soon! Have a good day!
