### ISSUE TITLE
CONTRIBUTING.md links broken.

### ISSUE THREAD

**Issue by jzabala** [okgrow/react-native-copilot#46]
Reading the contribution file I noticed the links are broken.

Looking through your organization I found what I think are the new links:

[contribution guidelines](https://github.com/okgrow/guides/blob/master/docs/OpenSource-Contributing.md)

[Code of Conduct](https://github.com/okgrow/guides/blob/master/docs/OpenSource-CodeOfConduct.md)

If you think that is right I can create a PR for that.

**Comment by RichardLitt** [comment]
Definitely right. Sorry about that!

A PR would be great; I'm happy to do that, too, if you'd rather. Let me know. :)

**Comment by jzabala** [comment]
@RichardLitt don't worry. I'll be happy to create the RP :D

**Comment by RichardLitt** [comment]
Thank you, @jzabala!
