### ISSUE TITLE
Is there a way to make the element of the current CopilotStep touchable/pressable?

### ISSUE THREAD

**Issue by AngSin** [okgrow/react-native-copilot#48]
Hi is it possible for me to be able to allow the users to click on touchable elements in the current CopilotStep? Right now even though it has a white background while everywhere else on the screen is black, it is still not possible to click on that element. I have tried both 'view' and 'svg' overlay's.

Would greatly appreciate your help!

**Comment by jzabala** [comment]
I thinks this is the same as issue #6

**Comment by AngSin** [comment]
Yes @jzabala, I'll close this but is that feature in progress?

**Comment by mohebifar** [comment]
I remember there was some inconsistency between Android and iOS that was blocking the progress on this feature; however, I'll try to look into this as the next task.

**Comment by AngSin** [comment]
@mohebifar Thanks!

**Comment by pribeh** [comment]
Any update on this?

**Comment by yanivnizry** [comment]
Hi,any update on this feature ?

**Comment by mohebifar** [comment]
There's a PR for this that is in review #71

**Comment by iujisato** [comment]
@AngSin @jzabala @pribeh @yanivnizry 
I've made a brief explanation on how I'm thinking in approaching this issue, if you guys want to see if my approach can help in your use cases you can check it on https://github.com/mohebifar/react-native-copilot/pull/71#issuecomment-704535398

**Comment by Aryk** [comment]
If you still need to be able to interact with the highlighted area, I wrote a library to do that and perform the transitions natively. Maybe it's helpful for someone:

https://github.com/tribefyhq/react-native-interactive-walkthrough
