### ISSUE TITLE
can it work with Stack Navigator?

### ISSUE THREAD

**Issue by yoavapi** [okgrow/react-native-copilot#51]
if so, how? could not make it work :(

**Comment by bemazo** [comment]
good question, after I enabled copilot on a screen all options from navigationOptions are ignored.
Navigaton bar is then empty.

**Comment by naffiq** [comment]
Looks like `copilot` doesn't pass static properties, as, for example, `react-redux`'es connect does.

**Comment by mohebifar** [comment]
I've never used rn-copilot with stack navigators. I think it can be fixed by doing a "static props hoist". Am I correct?

**Comment by naffiq** [comment]
@mohebifar yep, or simpler workaround for react-navigation without extra dependencies:

```javascript
import React from 'react';
import {copilot} from '@okgrow/react-native-copilot'

class SuperCoolScreen extends React.Component {
  static navigationOptions = {
    // Header configs or whatever
  }

  componentDidMount() {
    this.props.start();
  }

  render() {
    // Your screen view
  }
}

const SuperCoolScreenExplained = copilot()(SuperCoolScreen);

Object.assign(SuperCoolScreenExplained, {
  navigationOptions: SuperCoolScreen.navigationOptions
});

export default SuperCoolScreenExplained;

```

**Comment by mohebifar** [comment]
Addressed in #59

**Comment by ernymarvind** [comment]
Im using `CopilotStep` on a stack navigation as well but  is not showing when calling `this.props.start();`

Do you have any idea on how to make it work? Thanks!

**Comment by mohebifar** [comment]
@ernymarvind You have to somehow make the `StackNavigator` pass the `copilot` prop to the outermost `View` that's rendered by it.

[Take a look at this](https://github.com/okgrow/react-native-copilot#custom-components-as-steps)

**Comment by mohebifar** [comment]
[The workaround suggested by](https://github.com/okgrow/react-native-copilot/issues/51#issuecomment-405270922) @naffiq should not be needed anymore with version +2.4.1.

**Comment by rezapiryghadim** [comment]
> ```js
>   navigationOptions: SuperCoolScreen.navigationOptions
> ```

it't not working for me ,

![Simulator Screen Shot - iPhone 8 - 2019-03-19 at 15 06 24](https://user-images.githubusercontent.com/10910508/54603238-0b154980-4a59-11e9-821d-66fb5b229d29.png)




here is my navigationOptions

`    static navigationOptions = ({navigation}) => ({
        title: __('schedule.index.screen_title'),
        headerStyle: [(Platform.OS === 'android') ? {height: 80, paddingTop: 20} : null],
        headerBackTitle: null,
        headerRight : (
                <CopilotStep text={__('app_tutorial.home.2')} order={1} name="upcoming">
                    <WalkthroughableView>
                        <View>
                            <TouchableOpacity
                                activeOpacity       =   { .9 }
                                onPress             =   { navigation.getParam('navigateToSettings') }
                                hitSlop             =   {{ top: 10, bottom: 10, left: 40, right: 15 }}
                                style               =   {{ paddingRight: 15 }}
                            >
                                <Image
                                    source  =   { images.icons.settings_icon }
                                    style   =   {{ width : 18, height: 18, resizeMode : 'contain'}}
                                />
                            </TouchableOpacity>
                        </View>
                    </WalkthroughableView>
                </CopilotStep>
        )
    })`

and here is end of my code : 

`
const SuperCoolScreenExplained = connect(mapStateToProps, mapDispatchToProps)(copilot({
    animated: Platform.OS === 'android' ? false : true,
})(Schedule));

// Pass screen's navigation options to newly created HOC
Object.assign(SuperCoolScreenExplained, {
    navigationOptions: Schedule.navigationOptions
});

export default SuperCoolScreenExplained;
`

and i getting this error : 

**TypeError : Cannot read property 'getCurrentStep' of undefined **

**Comment by nehanilsoni** [comment]
Do we have a solution for the above issue yet? I too am getting the following error - 

TypeError: Cannot read property 'getCurrentStep' of undefined

**Comment by mingxin-yang** [comment]
@mohebifar 
Do we have a solution for the above issue yet?
```
TypeError: Cannot read property 'getCurrentStep' of undefined
```

**Comment by nhimspec** [comment]
Hello, Do we have a solution for this issues yet?
I cant use CopilotStep component on static navigationOptions.
`TypeError: Cannot read property 'getCurrentStep' of undefined`

**Comment by AbdulMoizJazsoft** [comment]
Is any have solution?

**Comment by AbdulMoizJazsoft** [comment]
you have to export your component like this.
export default connect(
    mapStateToProps,
    mapDispatchToProps,
)(
    copilot({
        animated: true, // Can be true or false
        overlay: 'svg',
        marginTop: 50,
    })(ProfileForm),
)
