### ISSUE TITLE
First Step Highlight frame not visible on start()

### ISSUE THREAD

**Issue by klapperkopp** [okgrow/react-native-copilot#52]
Hi,
I have this issue that even with the example app, it does not behave as it does in the screenshot in the readme.md. The first step elment never gets highlighted on a start().

**Expected behavior:**
First Step Element gets highlighted.

**Actual behavior:**
First element does not get highlighted. It only does, when you go one step further and then go back to previous.

![bug](https://user-images.githubusercontent.com/11021127/42767654-d2c28022-891d-11e8-975e-072ccb288ce2.gif)

**Suggested solution:**
I looked into it and found that if you change the following line 143 in copilot.js, it works:

old line:
`await this.setCurrentStep(currentStep, false);`
 
changed to:
`await this.setCurrentStep(currentStep, true);`

Questions: are there any drawbacks on triggering the `moveToCurrentStep()` also on `start()`? Or why was is this not done at the moment?

Update: I added a pull request for this. Just in case. :)

**Comment by klapperkopp** [comment]
That is entirely possible. I couldn't use `overlay: 'svg'`  , because it gave me some kind of error. So I sticked with `overlay: 'view'`.
Will try to get it running and check with svg again.

**Comment by RichardLitt** [comment]
@klapperkopp This should work now! Thanks for pointing it out. Let us know if it doesn't.
