### ISSUE TITLE
Can you support i18n ?

### ISSUE THREAD

**Issue by yanivnizry** [okgrow/react-native-copilot#61]
Hi,
I would really like to use this package but i need to use it with different language.
Will it be possible to make the few words that are hard coded ( next,skip,previous ) to be props ?

Thanks,
Yaniv

**Comment by mohebifar** [comment]
Currently, there's no such i18n support, but you can make your own [custom tooltip component](https://github.com/okgrow/react-native-copilot#custom-tooltip-component).

You can use the [default tooltip component](https://github.com/okgrow/react-native-copilot/blob/master/src/components/Tooltip.js) as a starting point.

**Comment by NilsBaumgartner1994** [comment]
I've solved this problem the following way. I created at the copilot configs:

```
 labels: {
                previous: <CopilotLanguageButton languageHelperIdentifier={"tutorial.previous"} />,
                next: <CopilotLanguageButton languageHelperIdentifier={"tutorial.next"} />,
                skip: <CopilotLanguageButton languageHelperIdentifier={"tutorial.skip"} />,
                finish: <CopilotLanguageButton languageHelperIdentifier={"tutorial.finish"} />,
            },
```

Then inside my own CopilotLanguageButton i created this:

```
constructor(props) {
        super(props);
        this.languageHelperIdentifier = this.props.languageHelperIdentifier;
        let initialText = LanguageHelper.strings(this.languageHelperIdentifier);

        this.state = {
            initialText: initialText
        }
    }

    async updateForCorrectLanguage(){
        this.setState({
            initialText: LanguageHelper.strings(this.languageHelperIdentifier)
        });
    }

    componentDidMount() {
        this.updateForCorrectLanguage();
    }

    render() {
        return this.state.initialText;
    }
```

The Normal Speach Bubbles can be translated inside their own View easily.
Maybe this will help someone
