### ISSUE TITLE
Can I change color of backdrop when step is active?

### ISSUE THREAD

**Issue by yoavapi** [okgrow/react-native-copilot#63]

**Comment by mohebifar** [comment]
There is no straightforward way for doing that right now. The colors are actually hard-coded now:

[SvgMask.js#L105](https://github.com/okgrow/react-native-copilot/blob/master/src/components/SvgMask.js#L105)
[src/components/style.js#L73](https://github.com/okgrow/react-native-copilot/blob/master/src/components/style.js#L73)

**Comment by RichardLitt** [comment]
@yoavapi If you want to submit a PR to fix this, I think it'd be a good addition.

**Comment by yoavapi** [comment]
Thanks both, I think I’ll do.

**Comment by yoavapi** [comment]
added [PR67](https://github.com/okgrow/react-native-copilot/pull/67)

**Comment by RichardLitt** [comment]
Thanks, @yoavapi!
