### ISSUE TITLE
Could you publish 2.4.0...?

### ISSUE THREAD

**Issue by ohtangza** [okgrow/react-native-copilot#64]
The recent Android overlay PR influenced my app critically. Any plan to publish new version?

https://github.com/okgrow/react-native-copilot/commit/0ba1149f6d09f17682ece59c28d2a5274696b150

**Comment by RichardLitt** [comment]
For anyone else: bumped to 2.4.1 in https://github.com/okgrow/react-native-copilot/commit/f8e847248355083f9621c0a56fc67ce3dd88f7ef.

**Comment by mohebifar** [comment]
Just published `2.4.1`
