### ISSUE TITLE
Is there is any way to style Tooltip?

### ISSUE THREAD

**Issue by KavitaU** [okgrow/react-native-copilot#77]
Hi,

Please refer the attached screenshot where I want to change the Tooltip text, Tooltip backgroundColor, Next & Skip button styling, and Order number styling. 

![screen shot 2018-09-18 at 8 08 17 pm](https://user-images.githubusercontent.com/6149308/45695625-6a180580-bb7f-11e8-9f29-c56e3d67d54c.png)

**Comment by mohebifar** [comment]
Please refer to [Custom Tooltip Component](https://github.com/okgrow/react-native-copilot#custom-tooltip-component) and [Custom Step Number Component](https://github.com/okgrow/react-native-copilot#custom-step-number-component) in the "readme".
