### ISSUE TITLE
Use CoPilot in a FlatList

### ISSUE THREAD

**Issue by iCueto** [okgrow/react-native-copilot#8]
Hello, I wish to use copilot on a ListItem in FlatList, and I think that if I used it, the steps will be repeated in all ListItems when the FlatList Render... Someone, have a Idea how to used it in a FlatList?

Thanks!!

**Comment by mohebifar** [comment]
I assume you want a copilot step only for one of the FlatList items and not for all. If that's the case, you should be able to manually make one of the items, a copilot step.

```js
renderItem = ({ index, item }) => {
  if (index === 0) {
    // Render copilot step
  } else {
    // Render without copilot
  }
}
```

**Comment by iCueto** [comment]
Ohhh, Thank you! :-)
