### ISSUE TITLE
Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by terreb** [okgrow/react-native-copilot#85]
"react-native": "0.56.0",
"@okgrow/react-native-copilot": "^2.4.1",
simulator iPhone 6 with iOS 12.1

I get the warning "Stateless function components cannot be given refs. Attempts to access this ref will fail" when trying to wrap my custom functional component with walkthroughable. I haven't found any mentioning in the docs that react-native-copilot requires only stateful components to work with. Is there a way to highlight a stateless (functional) component?

**Comment by RichardLitt** [comment]
Good catch. We may need to document this, if react-nactive-copilot does only require only stateful components.

**Comment by mohebifar** [comment]
Copilot needs to access the `measure` function for the outermost "native" component i.e. <View />, <Image />, <Text />, etc. which requires `ref`s.

Does that mean that the use of functional component [here in the README](https://github.com/okgrow/react-native-copilot#custom-components-as-steps) is incorrect?

**Comment by AishwaryaSurana** [comment]
Were you able to highlight your custom components?

**Comment by terreb** [comment]
@mohebifar, the example in docs is correct. If I wrap my functional component inside a RN View like in the example you provided it works as expected. I just thought I could make walkthroughable my functional component directly passing it to the walkthroughable function.

@AishwaryaSurana, just wrap you component like in the link @mohebifar provided.
