### ISSUE TITLE
border radius / margin around target element

### ISSUE THREAD

**Issue by douglaswissett** [okgrow/react-native-copilot#86]
I'm trying to tidy up the measure function around the target button, any ideas?

Ideally there should be not excess where you can see pass the dark overlay...

<img width="145" alt="screen shot 2018-11-07 at 10 48 42" src="https://user-images.githubusercontent.com/15790783/48127220-17072880-e27b-11e8-8ad2-f01f91a9d996.png">

**Comment by douglaswissett** [comment]
I'm trying to tidy up the measure function around the target button, any ideas?

Ideally there should be not excess where you can see pass the dark overlay...

<img width="145" alt="screen shot 2018-11-07 at 10 48 42" src="https://user-images.githubusercontent.com/15790783/48127220-17072880-e27b-11e8-8ad2-f01f91a9d996.png">

**Comment by mohebifar** [comment]
This is actually not possible with the current mask implementation. We currently do not have any plans for supporting masks with custom shapes. PRs are welcome though!

**Comment by paragspacetotech** [comment]
hi, i was going through this problem. you can edit the file in 
/node_modules/react-native-copilot/dist/index.js
 
`var init_SvgMask = __esm({
       position,
       canvasSize
     }) => {
+      const cornerRadius = 10; // You can adjust this value based on the desired radius
       const positionX = position.x._value;
       const positionY = position.y._value;
       const sizeX = size.x._value;
       const sizeY = size.y._value;
-      return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${positionX},${positionY}H${positionX + sizeX}V${positionY + sizeY}H${positionX}V${positionY}Z`;

+    return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0Z
+    M${positionX + cornerRadius}, ${positionY}
+    H${positionX + sizeX - cornerRadius} 
+    Q${positionX + sizeX}, ${positionY} ${positionX + sizeX}, ${positionY + cornerRadius} 
+    V${positionY + sizeY - cornerRadius} 
+    Q${positionX + sizeX}, ${positionY + sizeY} ${positionX + sizeX - cornerRadius}, ${positionY + sizeY} 
+    H${positionX + cornerRadius} 
+    Q${positionX}, ${positionY + sizeY} ${positionX}, ${positionY + sizeY - cornerRadius} 
+    V${positionY + cornerRadius} 
+    Q${positionX}, ${positionY} ${positionX + cornerRadius}, ${positionY} 
+    Z`
     };`

![Screenshot_1698912510](https://github.com/mohebifar/react-native-copilot/assets/128686491/347952ff-dbb5-4e4b-bd4e-aeb4d781f3ab)

**Comment by carl0shd** [comment]
> hi, i was going through this problem. you can edit the file in /node_modules/react-native-copilot/dist/index.js
> 
> `var init_SvgMask = __esm({ position, canvasSize }) => {
> 
> * ```
>    const cornerRadius = 10; // You can adjust this value based on the desired radius
>    const positionX = position.x._value;
>    const positionY = position.y._value;
>    const sizeX = size.x._value;
>    const sizeY = size.y._value;
>   ```
> 
> * ```
>    return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${positionX},${positionY}H${positionX + sizeX}V${positionY + sizeY}H${positionX}V${positionY}Z`;
>   ```
> 
> * return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0Z
> * M${positionX + cornerRadius}, ${positionY}
> * H${positionX + sizeX - cornerRadius}
> * Q${positionX + sizeX}, ${positionY} ${positionX + sizeX}, ${positionY + cornerRadius}
> * V${positionY + sizeY - cornerRadius}
> * Q${positionX + sizeX}, ${positionY + sizeY} ${positionX + sizeX - cornerRadius}, ${positionY + sizeY}
> * H${positionX + cornerRadius}
> * Q${positionX}, ${positionY + sizeY} ${positionX}, ${positionY + sizeY - cornerRadius}
> * V${positionY + cornerRadius}
> * Q${positionX}, ${positionY} ${positionX + cornerRadius}, ${positionY}
> * Z` };`
> 
> ![Screenshot_1698912510](https://private-user-images.githubusercontent.com/128686491/279909448-347952ff-dbb5-4e4b-bd4e-aeb4d781f3ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjEzNTcsIm5iZiI6MTcxNTAyMTA1NywicGF0aCI6Ii8xMjg2ODY0OTEvMjc5OTA5NDQ4LTM0Nzk1MmZmLWRiYjUtNGU0Yi1iZDRlLWFlYjRkNzgxZjNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxODQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDJjY2QxYjdmYjI2OTcyZDE5ODQwMzEzYTU0YWQ5MGI2YWZmNzg2MzQ0MGUzMWJjZWQ1ZmEzOTIzOTM3ZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9TqEYKh3WqSACcFWl8VX76OA5P3KGQsKroIBUo3QMOc)

in case anyone has a hard time copying the changes that @paragspacetotech does, this is the patch-package file

```diff --git a/node_modules/react-native-copilot/dist/index.js b/node_modules/react-native-copilot/dist/index.js
index b9127da..ef60d7b 100644
--- a/node_modules/react-native-copilot/dist/index.js
+++ b/node_modules/react-native-copilot/dist/index.js
@@ -188,11 +188,12 @@ var init_SvgMask = __esm({
       position,
       canvasSize
     }) => {
+      const cornerRadius = 12;
       const positionX = position.x._value;
       const positionY = position.y._value;
       const sizeX = size.x._value;
       const sizeY = size.y._value;
-      return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${positionX},${positionY}H${positionX + sizeX}V${positionY + sizeY}H${positionX}V${positionY}Z`;
+      return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${positionX + cornerRadius}, ${positionY}H${positionX + sizeX - cornerRadius}Q${positionX + sizeX}, ${positionY} ${positionX + sizeX}, ${positionY + cornerRadius}V${positionY + sizeY - cornerRadius}Q${positionX + sizeX}, ${positionY + sizeY} ${positionX + sizeX - cornerRadius}, ${positionY + sizeY}H${positionX + cornerRadius}Q${positionX}, ${positionY + sizeY} ${positionX}, ${positionY + sizeY - cornerRadius}V${positionY + cornerRadius}Q${positionX}, ${positionY} ${positionX + cornerRadius}, ${positionY}Z`;
     };
     SvgMask = ({
       size,
```

**Comment by ambreenzubari** [comment]
Hi, you can achieve this just by using a props **svgMaskPath**
it is use for the custom mask, like if you want a circle as a mask, or want different masks for different order numbers you can use that.

like it u want to add some radius, around the mask you can use this:
  ```
const circleSvgPath = event => {
     const {position, canvasSize, size} = event;
      const    cornerRadius = 20;
      const positionX = position.x._value;
      const positionY = position.y._value;
      const sizeX = size.x._value;
      const sizeY = size.y._value;     

      return `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${
        positionX + cornerRadius
      }, ${positionY}H${positionX + sizeX - cornerRadius}Q${
        positionX + sizeX
      }, ${positionY} ${positionX + sizeX}, ${positionY + cornerRadius}V${
        positionY + sizeY - cornerRadius
      }Q${positionX + sizeX}, ${positionY + sizeY} ${
        positionX + sizeX - cornerRadius
      }, ${positionY + sizeY}H${positionX + cornerRadius}Q${positionX}, ${
        positionY + sizeY
      } ${positionX}, ${positionY + sizeY - cornerRadius}V${
        positionY + cornerRadius
      }Q${positionX}, ${positionY} ${positionX + cornerRadius}, ${positionY}Z`;
    }
```

u can pass cornerRadius whatever you want.

And this is how you can declare it:
```
<CopilotProvider
      svgMaskPath={circleSvgPath}
>
```
