### ISSUE TITLE
Not Opening 

### ISSUE THREAD

**Issue by Deep1210** [okgrow/react-native-copilot#88]
Added all the things as mentioned but not working. It is not showing anything .

**Comment by mohebifar** [comment]
Please describe what you’ve already tried. Share some part of the code.

Are you getting any errors? Have you tried running [the example](https://github.com/okgrow/react-native-copilot/blob/master/example/App.js) or comparing your code with it?

**Comment by Deep1210** [comment]
return (
            <View style={styles.mainContainer}>
                <View style={styles.toolbar}>
                    <TouchableOpacity style={styles.backButtonTouch} onPress={()=>this.props.start()}>
                        <CopilotStep text="This is a hello world example!" order={1} name="hello">
                            <WalkthroughableText style={styles.tabItem}>
                                <Image style={styles.button} source={require('../assets/settingswheel.png')} />
                            </WalkthroughableText>
                        </CopilotStep>
                    </TouchableOpacity>
                </View>
           </View>
)

**Comment by Deep1210** [comment]
Here above is the code where i am using it but it doesn't show anything

**Comment by RichardLitt** [comment]
@Deep1210 I edited your comment to make it a code block, so that it renders correctly. For more on how GitHub uses Markdown, check out [this guide](https://guides.github.com/features/mastering-markdown/).

**Comment by mohebifar** [comment]
@Deep1210 I wonder why you have wrapped the copilot step inside a `TouchableOpacity`. Do you want to use your first walkthrough step to tap to initiate the walkthrough?

**Comment by Deep1210** [comment]
Sorry to disturb but now it is running i have not started it in componentDidMount() function
