### ISSUE TITLE
highlight all components 

### ISSUE THREAD

**Issue by dverma4u** [okgrow/react-native-copilot#92]
Can anyone tell me how can i achieve something like this with this library?

![a5222860-f332-4d41-a465-0ca045e31f3a](https://user-images.githubusercontent.com/31440793/48904341-11692f80-ee84-11e8-9893-326c1225e052.jpg)

**Comment by mohebifar** [comment]
I don't think this question is really related to this repository. But you can do something similar to what [copilot's svg mask](https://github.com/okgrow/react-native-copilot/blob/master/src/components/SvgMask.js) does. Make an SVG filled with a semi-transparent overlay using a vector software like Inkscape or Illustrator then cut enough circle holes inside it. Then use `react-native-svg` to render that SVG. [Determine the position of elements](https://facebook.github.io/react-native/docs/view#onlayout) then resize and reposition the holes in your SVG.
