### ISSUE TITLE
Is react-native-svg optional or required?

### ISSUE THREAD

**Issue by siderakis** [okgrow/react-native-copilot#95]
The documentation says react-native-svg is optional, but it seems to be required to compile without error.

Thanks! :-)

**Comment by mohebifar** [comment]
It's recommended to use the svg mask due to faster animations. But, if you prefer not to link new libraries, you can use the view mask.

```js
copilot({
  overlay: 'view', // or 'svg' if you have react-native-svg installed and linked
})(RootComponent)
```

**Comment by DavideValdo** [comment]
<img width="308" alt="screen shot 2019-02-12 at 18 50 04" src="https://user-images.githubusercontent.com/26572302/52656631-0cea6b00-2ef7-11e9-8b86-656278bc6ab5.png">

Code:

```
export default copilot({
  overlay: 'view',
  animated: true,
})(connect ()(ItemRUDRow))
```
